version: "3"
services:
  db:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - /home/david/Escritorio/DockerVolumes/mongodata:/data/db
    networks:
      - sopr1-net

  backend:
    build: ./back-end
    container_name: backend-go
    environment:
      MONGO_USERNAME: mongoadmin
      MONGO_PASSWORD: 1234
      MONGO_HOST: db
    ports:
    - "8000:8000"
    restart: always
    depends_on:
    - db
    networks:
    - sopr1-net

  frontend:
    build: ./front-end
    container_name: frontend-react-nginx
    ports:
    - "81:80"
    restart: always
    depends_on:
    - backend
    networks:
    - sopr1-net

volumes:
  mongodata:  

networks:
  sopr1-net:
    driver: bridge